### ISSUE TITLE
[Idia] Make config out of build proccess.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [CarbonoDev/quasar-dotenv#5]
Hello!
I have similar case some days ago to import in project with quasar some variables by .json.
But as I read readme.md here, variables imports at build time.
Very interesting to make them configurable on server without build process.
To get them by some config file, without need to rebuild if config changes.

It's need when server is running, and uses already builded code, to configure.

I made it in my project with separate json file. But not very good code.
If you interest in this, we can talk.

**Comment by marcorivm** [comment]
Hey @Dmitrij-Polyanin thanks for your interest. Please do share the code or feel free to make a pull request with a partial implementation and we can discuss further.

**Comment by DmitrijOkeanij** [comment]
After I wrote issue here I found normal decision for me.  
I have no time to analize code here and make pull request, but I can wrote Idea how to make config out of build proccess.

I have 2 json file.
1. config-prod.json
2. config-dev.json

With this simple syntax.

```
var config = {
  API: 'http://localhost:7001',
  UploadedImages: 'http://localhost:7001/UploadImages',
  SiteName: 'SiteName'
}
```

And add link to this file in `index.template.html`. 
` <script type="text/javascript" src="/config.js"></script>`

Now adding this file to output directory.

```
extendWebpack(cfg) {
        if(ctx.dev) {
          cfg.plugins.push( new CopyWebpackPlugin([{from: 'config-dev.js', to:'config.js'}]));
        } else {
          cfg.plugins.push( new CopyWebpackPlugin([{from: 'config-prod.js',to:'config.js'}]));
        }
      }
```

I am not sure how correct way implement it with env file, may be to tranform env to json... But after compile it will be json to config enf on the fly.
