### ISSUE TITLE
Bug: user defined env variables are stored in process.env.parsed

### ISSUE THREAD

**Issue by aflatoon2874** [CarbonoDev/quasar-dotenv#6]
The user defined env variables are stored in `process.env.parsed` which is incorrect. After examining the code I found that `Dotenv.config` returns the result with a key `parsed`. To fix the issue line 11 in `index.js` should be `const parsedEnv = config(configOptions).parsed`. 

Kindly fix the issue.
Thanks

**Comment by marcorivm** [comment]
You are correct, although it still works since the env variables are also loaded to process.env, we are just adding an extra variable "parsed"

**Comment by aflatoon2874** [comment]
No it does not work. None of my environment variables were available via
process.env. Had it worked there was no reason for me to debug your code.
Can you explain which part of the code also loads variables to the
process.env object? Thanks

**Comment by marcorivm** [comment]
By calling dotenv.config it will load the variables to process.env
https://github.com/motdotla/dotenv#config
> config will read your .env file, parse the contents, **assign it to process.env**, and return an Object with a parsed key containing the loaded content or an error key if it failed.

Then on https://github.com/CarbonoDev/quasar-dotenv/blob/master/index.js#L27 it will get parsed again from process.env this time. This requires you to have a .env.example file which is a good practice anyways.

Anyways the code was updated to use  `.parsed` on the first loop so it should work without the .env.example file
