### ISSUE TITLE
Support boolean true/false

### ISSUE THREAD

**Issue by ajcastro** [CarbonoDev/quasar-dotenv#7]
I tried adding a boolean variable like
```
LOGS_ENABLED=false
```
but it returns string `"false"` instead of boolean `false`.

**Comment by marcorivm** [comment]
@ajcastro which version of quasar are you using? There are newer alternatives for v1 and v2
For v1.0 and above please check
https://github.com/quasarframework/app-extension-dotenv

And if you are working with a CI env
https://github.com/marcorivm/quasar-app-extension-system-environment-variables

I'll be marking this one as readonly soon
