### ISSUE TITLE
JSON.stringify

### ISSUE THREAD

**Issue by jrglaber** [CarbonoDev/quasar-dotenv#8]
In new version of Quasar don't use JSON.stringify more for envs variables.

Needs change quasar-dontenv/index.js file, in line 27, update from:

`quasarEnv[key] = JSON.stringify(process.env[key])`

to:

`quasarEnv[key] = process.env[key]`.

I test in local and it work!!!

**Comment by marcorivm** [comment]
This plugin is for quasar pre v1.0, for v1.0 and above please check 
https://github.com/quasarframework/app-extension-dotenv

And if you are working with a CI env
https://github.com/marcorivm/quasar-app-extension-system-environment-variables
