### ISSUE TITLE
There are string retrun with doublequote

### ISSUE THREAD

**Issue by garam-park** [CarbonoDev/quasar-dotenv#9]
I expected that `.env.example`(A) make `process.env` (B), but (C).
This make me handle unexpected value with doublequote.

### A
```
# .env.example
STR=HELLO WORLD
```
### B
```
// process.env.STR : 'HELLO WORLD'
console.log(`process.env.STR : ${process.env}`);
```

### C
```
// process.env.STR : '"HELLO WORLD"'
console.log(`process.env.STR : ${process.env}`);
```

**Comment by marcorivm** [comment]
Which quasar version are you using?  

The PR look pretty good, I'll test it later and merge it

**Comment by marcorivm** [comment]
There are newer alternatives for v1 and v2
For v1.0 and above please check
https://github.com/quasarframework/app-extension-dotenv

And if you are working with a CI env
https://github.com/marcorivm/quasar-app-extension-system-environment-variables

I'll be marking this one as readonly soon
